'use strict';

module.exports = {
	checkbox: 'Checkbox',
	colorPicker: 'ColorPicker',
	input: 'Input',
	link: 'Link',
	select: 'Select',
	multiselect: 'Multiselect',
	selectMultilevel: 'SelectMultilevel',
	switch: 'Switch',
	text: 'Text',
	textarea: 'Textarea',
	checkList: 'CheckList',
	multiInput: 'MultiInput',
	chip: 'Chip',
	userChip: 'UserChip',
	statusChip: 'StatusChip',
	mediumChip: 'MediumChip',
	code: 'Code',
	dateTimePicker: 'DateTimePicker',
	fieldsArray: 'FieldsArray',
	asyncWrapper: 'AsyncWrapper',
	map: 'Map',
	html: 'HTML',
	userSelector: 'UserSelector',
	image: 'Image',
	userImage: 'UserImage',
	iconSelector: 'IconSelector',
	preview: 'Preview',
	selectForm: 'SelectForm'
};
